- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java
> Skip analysis if report does not exist

- .gitignore
- README.md
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckPlugin.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckConstants.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckUtils.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/base/DependencyCheckUtilsTest.java
Fixes #22
Makes the minimum scores for the severities configurable.
> Make severities configurable

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/rule/KnownCveRuleDefinition.java
https://github.com/stevespringett/dependency-check-sonar-plugin/issues/83
> add owasp-a9 tag

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java
At the moment we have no metric for this issue, but we should count to have a correct `incrementCount` function
> Count infoIssues

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckPlugin.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckMeasureComputer.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckMetric.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReasonSearcher.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/reason/DependencyReasonSearcherTest.java
> Use measurecomputer

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckUtils.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/ReportParser.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/ReportParserException.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/Analysis.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/Dependency.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/Evidence.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/Identifier.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/ProjectInfo.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/Vulnerability.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/parser/ReportParserTest.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/reason/DependencyReasonSearcherTest.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/reason/GradleDependencyReasonTest.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/reason/MavenDependencyReasonTest.java
Throw an error for an unsupported report.
> Be more NullSafe, when parse Report

- examples/multi-module-maven/pom.xml
- examples/single-module-maven/pom.xml
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/ReportParser.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/Cvss.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/CvssV2.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/CvssV3.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/Vulnerability.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/MavenDependencyReason.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/parser/ReportParserTest.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/parser/element/VulnerabilityTest.java
- sonar-dependency-check-plugin/src/test/resources/report/dependency-check-report-400.xml
- sonar-dependency-check-plugin/src/test/resources/report/dependency-check-report-500.xml
> Implements schema changes from dependency-check 5

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckUtils.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/ReportParser.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/base/DependencyCheckUtilsTest.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/parser/ReportParserTest.java
TODO:
- Tests for severityToScore
> WIP: Parse reports without score and severity + calculate score from severity

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckMetrics.java
Change Metric Direction  of "Vulnerable Component Ratio" and "Inherited Risk Score"
Should fix #178
> Change Metric Direction 

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/XMLReportParserHelper.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/deserializer/MavenDependencyDeserializer.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReasonSearcher.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/report/ReportFile.java
> Minor changes

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckConfiguration.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckConstants.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/DependencyCheckPluginTest.java
> Smooth breaking change

- examples/multi-module-maven/pom.xml
- examples/multi-project-csproj/Dockerfile
- examples/single-module-gradle/build.gradle
- examples/single-module-kotlin-dsl-gradle/build.gradle.kts
- examples/single-module-maven/pom.xml
- examples/single-module-nodejs/README.md
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java
> Update examples to dependency-check 5.3

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/GradleDependencyReason.java
> GradleDependencyReason is to noisy

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/Identifier.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/NPMDependencyReason.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/parser/element/IdentifierTest.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/reason/NPMDependencyReasonTest.java
> npm package inforamtion without version

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReasonSearcher.java
> Correct gradle typo log message

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReasonSearcher.java
> Correct spelling

- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckUtils.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/Dependency.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReason.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReasonSearcher.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/GradleDependencyReason.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/Language.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/MavenDependencyReason.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/NPMDependencyReason.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/base/DependencyCheckUtilsTest.java
> Prefer configuration files based on the dependency language

- examples/multi-module-maven/pom.xml
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/CvssV2.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/CvssV3.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/DependencyCheckSensorTest.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/parser/ReportParserTest.java
- sonar-dependency-check-plugin/src/test/resources/reportMultiModuleMavenExample/dependency-check-report.json
- sonar-dependency-check-plugin/src/test/resources/reportMultiModuleMavenExample/dependency-check-report.xml
> Support dependency-check 6.0.0

- .github/dependabot.yml
- sonar-dependency-check-plugin/package-lock.json
- sonar-dependency-check-plugin/package.json
Update node dependencies and adjust dependabot
> Node Dependencies and Dependabot adjustment

- .github/workflows/testing.yml
- pom.xml
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckConstants.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/XMLReportParserHelper.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/report/ReportFormat.java
- sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/report/XmlReportFile.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/DependencyCheckSensorTest.java
- sonar-dependency-check-plugin/src/test/java/org/sonar/dependencycheck/parser/XMLReportParserHelperTest.java
> Restore JDK8 compatibility

- sonar-dependency-check-plugin/conf/webpack.common.js
- sonar-dependency-check-plugin/src/main/js/report_page/components/DependencyCheckReportApp.js
> Remove unsupported sonar-components and sonar-helpers

- sonar-dependency-check-plugin/src/main/js/report_page/components/DependencyCheckReportApp.js
Fix #359 #904 #765
Please note that JavaScript does not work on this page. Inline-Java-Script is blocked by SonarQube.
> Open report in a separate window

- examples/single-module-maven/pom.xml
- sonar-dependency-check-plugin/src/test/resources/reason/build.gradle
- sonar-dependency-check-plugin/src/test/resources/reason/build.gradle.kts
- sonar-dependency-check-plugin/src/test/resources/reason/pom.xml
> Remove or replace reportPath
